apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1
  labels:
    app: testapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp1
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
        - name: testapp1
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testapp1
spec:
  selector:
    app: testapp1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31080
  type: NodePort
